name: Build Single Executable

on:
  push:
    tags:
      - 'v*' # Chạy build tự động khi bạn tạo release tag (VD: v1.0, v1.1)
  workflow_dispatch: # Cho phép bấm nút "Run workflow" thủ công trên giao diện GitHub

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    # 2. Đóng gói thành file .exe độc lập
    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --noconfirm --onefile --windowed --name="GitHub SSH & Git Identity Manager" --icon="app_icon.ico" main.py 

    # 3. Đẩy file .exe lên GitHub Artifacts để tải về
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: GitHubSSHSetup-Exe
        path: dist/main.exe